### ISSUE TITLE
VJTAG with Altera board

### ISSUE THREAD

**Issue by lapnd** [michg/pyocdriscv32#1]
Hi,
I'm trying to use vjtag with DE10Lite board. My expectation is with single USB connection, we can both programming the board as well as debuging the app run on murax core.
is that possible with this project https://github.com/michg/pyocdriscv32/tree/master/murax/quartus/virtual?
I had tried it but I'm not sure this vjtag support this
```sh
10M50.tap
Info : set servers polling period to 50ms
Info : No lowlevel driver configured, using ftdi
Info : usb blaster interface using libftdi
Info : This adapter doesn't support configurable speed
Info : JTAG tap: 10M50.tap tap/device found: 0x031050dd (mfg: 0x06e (Altera), part: 0x3105, ver: 0x0)
Info : starting gdb server for saxon.cpu0 on 3333
Info : Listening on port 3333 for gdb connections
Halting processor
requesting target halt and executing a soft reset
 done
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : accepting 'gdb' connection on tcp/3333
Info : New GDB Connection: 1, Target saxon.cpu0, state: halted
Warn : Prefer GDB command "target extended-remote :3333" instead of "target remote :3333"
Info : Halt timed out, wake up GDB.
Warn : target saxon.cpu0 is not halted (gdb fileio)
openocd: src/target/vexriscv.c:1233: vexriscv_read_memory: Assertion `target->state == TARGET_HALTED' failed.
Aborted (core dumped)
```

**Comment by michg** [comment]
Hello lapnd,
it seems, that you are trying to use openocd over virtual jtag with the murax core. 
To my knowledge openocd does not support virtual jtag for murax.
The pyocdriscv32 scripts are intended to be used standalone, they do not communicate with openocd or gdb. So for your usecase you will probably have to add virtual jtag support to openocd, similar to JtagOCDEngine in dbgjtag.py.

**Comment by lapnd** [comment]
Thank you @michg 
I got your points!
